# Generated by Django 4.2.3 on 2023-07-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'managed': False},
        ),
    ]
