# Generated by Django 4.2.3 on 2023-07-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsmodel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsmodel',
            table='newsmodel',
        ),
    ]
